AWSTemplateFormatVersion: '2010-09-09'
Description: Minimal IAM property test for doorbell Lab 7
Parameters:
  IotTopicPrefix:
    Type: String
    Default: doorbell
Resources:
  CommonFunctionPolicy:
    Type: AWS::IAM::ManagedPolicy
    Properties:
      ManagedPolicyName: test-common-policy-doorbell-lab7
      PolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Action:
              - logs:CreateLogGroup
              - logs:CreateLogStream
              - logs:PutLogEvents
            Resource: '*'
  PublishCommandFunctionRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Action:
              - sts:AssumeRole
            Effect: Allow
            Principal:
              Service:
                - lambda.amazonaws.com
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AWSLambdaBasicExecutionRole
        - !Ref CommonFunctionPolicy
      Policies:
        - PolicyName: PublishCommandFunctionRolePolicy1
          PolicyDocument:
            Statement:
              - Effect: Allow
                Action:
                  - iot:Publish
                Resource: !Sub 'arn:aws:iot:${AWS::Region}:${AWS::AccountId}:topic/${IotTopicPrefix}/*'
